### PR TITLE
Adding the ability to pass in a cidr to the tree

### PR DESCRIPTION
**Pull request by O-Mutt**
I have a use case where i would like to be able to pass in a cidr to the tree but it seems that functionality may not currently be supported... so i wrote some 👍 

I added a unit test with some assertions to hopefully give context to the change. I may need to update the README as well at some point.

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
This looks like a great addition @Mutmatt :)

Only request is to add a sentence to the README noting CIDR support.

**Comment by O-Mutt** [comment]
@transitive-bullshit Added some info to the docs for us 😺

**Comment by O-Mutt** [comment]
Bump. CanIGettaMerge? 🙏

**Comment by transitive-bullshit** [comment]
Sorry for taking so long on this -- just merged and published as `v1.0.2`.

Thanks!!

**Pull request merged**
