### PR TITLE
Expand test coverage

### PR DESCRIPTION
**Pull request by kusold**
👋 

This PR expands test coverage. Let me know how you feel about having the IPv6 tests in here, I can easily remove them since IPv6 is not fully supported.

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Thanks @kusold!

Can you update `.travis.yml` to make sure CI passes?

Let's maintain the same level of Node support (so no arrow functions) since it's such a simple module.

**Comment by kusold** [comment]
@transitive-bullshit I updated the CI to test against all current LTS releases (4,6,8) and swapped to using `function` instead of arrows.

**Comment by feross** [comment]
@kusold FYI, Node 4 is not LTS anymore, it's actually unsupported. https://github.com/nodejs/Release#release-schedule

**Comment by kusold** [comment]
True. My reasoning was that since we are still testing on 0.10 & 0.11 then 4.x should also be tested. I'm indifferent either way and will let @transitive-bullshit make the call.

**Comment by feross** [comment]
@kusold Yep, that makes sense. I was just letting you know that Node 4 isn't LTS ;)

**Pull request merged**
